### PR TITLE
Eglif add receptor

### PR DESCRIPTION
**Pull request by AliceGem**
Added receptor 4 on E-GLIF neuron model

### CODE REVIEW

**Comment by AliceGem** [comment]
@Massimogri you tested and it's working?

**Comment by Massimogri** [comment]
@AliceGem I actually believed that was already working. 
However, I tried it and I found a segmentation error I can not delete.
Schermata da 2020-07-30 09-51-48

During the creation of gly-golgi connection it generates this error. In addition, after going back to the previous version of the JSON file I found this error too. It seems that the error is fixed there and I can't remove it. 

I tried the same JSON file with other scripts and works fine. If I create a new file with the same code of the one used to test the 4° receptor, the first time another error appeared `Annullato` and, after that, it went back to the `segmentation error`
Schermata da 2020-07-30 09-52-03

In order to test the 4° EGLIF I changed only the JSON file:
created a new `tau_syn4`
created a new `E_rev4`
In `receptors` I assigned 4 to `gly_cells`

**Comment by Massimogri** [comment]
@AliceGem Actually the same JSON file worked in other python scripts only if the weigth gly-golgi was set to zero. After setting this value different from zero, the error appeared and, even after resetting the weight to zero, the error was still there.

**Comment by AliceGem** [comment]
@Massimogri try now, it works for me (out of the scaffold). There were some typos.

**Comment by AliceGem** [comment]
I tested on this:

```
from nest import *
Install("cerebmodule")
SetKernelStatus({"overwrite_files": True})
pg = Create("poisson_generator", params={"rate": 50000.0})
n = Create("eglif_cond_alpha_multisyn", 4)
sd = Create("spike_detector", params={"to_file": True})
Connect(pg, [n[0]], syn_spec={'weight': 1000.0, 'delay': 1.0, 'receptor_type': 1})
Connect([n[0]], [n[1]], syn_spec={'weight': 1000.0, 'delay': 1.0, 'receptor_type': 2})
Connect([n[1]], [n[2]], syn_spec={'weight': 1000.0, 'delay': 1.0, 'receptor_type': 3})
Connect([n[2]], [n[3]], syn_spec={'weight': 1000.0, 'delay': 1.0, 'receptor_type': 4})
Connect(n, sd)
Simulate(100.0)
```

**Comment by Massimogri** [comment]
@AliceGem I tried to use my code with the scaffold and the connection gly-golgi works. 

However, I tried analysing the changes in conductance due to glycinergic stimulation and the changes between G3 and G4 were the same. So, I believed I had some errors in my code and I used your code with the addition of two multimeters.

```
from nest import *

Install("cerebmodule")
SetKernelStatus({"overwrite_files": True})
pg = Create("poisson_generator", params={"rate": 50000.0})
n = Create("eglif_cond_alpha_multisyn", 4)
sd = Create("spike_detector", params={"to_file": True})
Connect(pg, [n[0]], syn_spec={'weight': 1000.0, 'delay': 1.0, 'receptor_type': 1})
Connect([n[0]], [n[1]], syn_spec={'weight': 1000.0, 'delay': 1.0, 'receptor_type': 2})
Connect([n[1]], [n[2]], syn_spec={'weight': 1000.0, 'delay': 1.0, 'receptor_type': 3})
Connect([n[2]], [n[3]], syn_spec={'weight': 1000.0, 'delay': 1.0, 'receptor_type': 4})
Connect(n, sd)

m2 = Create("multimeter",
                    params = {"interval": 1.0,
                            "record_from": ["V_m", "I_dep", "I_adap","G3","G4"],
                            "withgid": True,
                            "to_file": True,
                            "label": "multimeter"})
m3 = Create("multimeter",
                    params = {"interval": 1.0,
                            "record_from": ["V_m", "I_dep", "I_adap", "G3","G4"],
                            "withgid": True,
                            "to_file": True,
                            "label": "multimeter"})

Connect(m2,[n[2]])
Connect(m3,[n[3]])

Simulate(100.0)
```

In n[3] neuron its G4 conductance doesn't change, while, n[2] changes both G3 and G4 (G4 and G3 change in the same way).
Seems that G4 is a replica of G3

**Comment by Massimogri** [comment]
https://github.com/dbbs-lab/cereb-nest/blob/ed4cd87851cbccc6bb97d7eafe6daa0e033bd8f7/eglif_cond_alpha_multisyn.cpp#L105

https://github.com/dbbs-lab/cereb-nest/blob/ed4cd87851cbccc6bb97d7eafe6daa0e033bd8f7/eglif_cond_alpha_multisyn.cpp#L108

I changed these two lines with `get_G4` and `get_DG4` and seems to work

**Comment by AliceGem** [comment]
Perfect, good catch! I close the issue.

**Pull request merged**
